// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home_screen.h"
#include "screens/ui_settings.h"
#include "screens/ui_audioconfig.h"
#include "screens/ui_playback.h"
#include "screens/ui_info.h"
#include "screens/ui_dateandtime.h"
#include "screens/ui_editslot1.h"
#include "screens/ui_schedule.h"
#include "screens/ui_playbackImage.h"
#include "screens/ui_recordingImage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1388130735);    // assets/icons8-setup-18.png
LV_IMG_DECLARE(ui_img_1649062918);    // assets/box-18-red.png
LV_IMG_DECLARE(ui_img_419196496);    // assets/icons8-schedule-24.png
LV_IMG_DECLARE(ui_img_336627466);    // assets/audio-24x24.png
LV_IMG_DECLARE(ui_img_1236581539);    // assets/time-24x24.png
LV_IMG_DECLARE(ui_img_1476654543);    // assets/icons8-info-24.png
LV_IMG_DECLARE(ui_img_play19x19_png);    // assets/play19x19.png
LV_IMG_DECLARE(ui_img_yes20x20_png);    // assets/yes20x20.png
LV_IMG_DECLARE(ui_img_no20x20_png);    // assets/no20x20.png
LV_IMG_DECLARE(ui_img_yes20x20xblack_png);    // assets/yes20x20xblack.png
LV_IMG_DECLARE(ui_img_playback_png);    // assets/PLAYBACK.png
LV_IMG_DECLARE(ui_img_recording_png);    // assets/RECORDING.png
LV_IMG_DECLARE(ui_img_paused_png);    // assets/PAUSED.png
LV_IMG_DECLARE(ui_img_drawer_open_png);    // assets/drawer_open.png
LV_IMG_DECLARE(ui_img_learning_png);    // assets/learning.png
LV_IMG_DECLARE(ui_img_drawer_open_image_png);    // assets/drawer_open_image.png
LV_IMG_DECLARE(ui_img_drawer_opening_png);    // assets/drawer_opening.png
LV_IMG_DECLARE(ui_img_drawer_closing_png);    // assets/drawer_closing.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
