// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_DRAWER_H
#define UI_DRAWER_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_drawer
extern void ui_drawer_screen_init(void);
extern void ui_drawer_screen_destroy(void);
extern lv_obj_t *ui_drawer;
extern lv_obj_t *ui_drawerOpen;
extern lv_obj_t *ui_learningAddcard;
extern lv_obj_t *ui_drawerOpenImage;
extern lv_obj_t *ui_draweropening;
extern lv_obj_t *ui_drawerclosing;
// CUSTOM VARIABLES
extern lv_obj_t *uic_drawer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

