// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_DATEANDTIME_H
#define UI_DATEANDTIME_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_dateandtime
extern void ui_dateandtime_screen_init(void);
extern void ui_dateandtime_screen_destroy(void);
extern lv_obj_t *ui_dateandtime;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_editSlotPanel;
extern lv_obj_t *ui_iconImage5;
extern lv_obj_t *ui_okLabel5;
extern lv_obj_t *ui_boxImage5;
extern lv_obj_t *ui_backLabel5;
extern lv_obj_t *ui_btnSaveEditslot;
extern lv_obj_t *ui_Panel_year;
extern lv_obj_t *ui_YearLabelEditslot;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Panel_month;
extern lv_obj_t *ui_MonthLabelEditslot;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Panel_date;
extern lv_obj_t *ui_DateLabelEditslot;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Panel_hour_date_time;
extern lv_obj_t *ui_HourLabelEditslot;
extern lv_obj_t *ui_Panel_min_date_time;
extern lv_obj_t *ui_MinLabelEditslot;
extern lv_obj_t *ui_Panel_second_date_time1;
extern lv_obj_t *ui_secondLabelEditslot2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

