// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_editslot = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_editSlotPanel = NULL;
lv_obj_t * ui_iconImage3 = NULL;
lv_obj_t * ui_okLabel3 = NULL;
lv_obj_t * ui_boxImage3 = NULL;
lv_obj_t * ui_backLabel3 = NULL;
lv_obj_t * ui_btnSaveEditslot = NULL;
lv_obj_t * ui_HourLabelEditslot = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_YearLabelEditslot = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_MonthLabelEditslot = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_DateLabelEditslot = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_MinLabelEditslot = NULL;
// event funtions

// build funtions

void ui_editslot_screen_init(void)
{
    ui_editslot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_editslot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_editslot);
    lv_obj_set_width(ui_Panel6, 428);
    lv_obj_set_height(ui_Panel6, 28);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editSlotPanel = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_editSlotPanel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_editSlotPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_editSlotPanel, 183);
    lv_obj_set_y(ui_editSlotPanel, 8);
    lv_label_set_text(ui_editSlotPanel, "EDIT SLOT 4");
    lv_obj_set_style_text_color(ui_editSlotPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_editSlotPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_editSlotPanel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconImage3 = lv_image_create(ui_editslot);
    lv_image_set_src(ui_iconImage3, &ui_img_1388130735);
    lv_obj_set_width(ui_iconImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconImage3, 9);
    lv_obj_set_y(ui_iconImage3, 5);
    lv_obj_add_flag(ui_iconImage3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLabel3 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_okLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okLabel3, 32);
    lv_obj_set_y(ui_okLabel3, 10);
    lv_label_set_text(ui_okLabel3, "OK (SETUP)");
    lv_obj_set_style_text_color(ui_okLabel3, lv_color_hex(0x41C173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_okLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_okLabel3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boxImage3 = lv_image_create(ui_editslot);
    lv_image_set_src(ui_boxImage3, &ui_img_1649062918);
    lv_obj_set_width(ui_boxImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boxImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boxImage3, 397);
    lv_obj_set_y(ui_boxImage3, 6);
    lv_obj_add_flag(ui_boxImage3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_boxImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backLabel3 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_backLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabel3, 339);
    lv_obj_set_y(ui_backLabel3, 10);
    lv_label_set_text(ui_backLabel3, "BACK (OPEN)");
    lv_obj_set_style_text_color(ui_backLabel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backLabel3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveEditslot = lv_button_create(ui_editslot);
    lv_obj_set_width(ui_btnSaveEditslot, 428);
    lv_obj_set_height(ui_btnSaveEditslot, 25);
    lv_obj_set_x(ui_btnSaveEditslot, 0);
    lv_obj_set_y(ui_btnSaveEditslot, 103);
    lv_obj_add_flag(ui_btnSaveEditslot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSaveEditslot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSaveEditslot, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSaveEditslot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSaveEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSaveEditslot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSaveEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSaveEditslot, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnSaveEditslot, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourLabelEditslot = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_HourLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabelEditslot, 181);
    lv_obj_set_y(ui_HourLabelEditslot, 71);
    lv_label_set_text(ui_HourLabelEditslot, "22");
    lv_obj_set_style_text_color(ui_HourLabelEditslot, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourLabelEditslot, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 67);
    lv_obj_set_y(ui_Label5, 50);
    lv_label_set_text(ui_Label5, "2026");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_editslot);
    lv_obj_set_width(ui_Panel7, 97);
    lv_obj_set_height(ui_Panel7, 28);
    lv_obj_set_x(ui_Panel7, 32);
    lv_obj_set_y(ui_Panel7, 36);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0xA4BFF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YearLabelEditslot = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_YearLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YearLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YearLabelEditslot, 67);
    lv_obj_set_y(ui_YearLabelEditslot, 50);
    lv_label_set_text(ui_YearLabelEditslot, "2026");
    lv_obj_set_style_text_color(ui_YearLabelEditslot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YearLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YearLabelEditslot, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 69);
    lv_obj_set_y(ui_Label8, 38);
    lv_label_set_text(ui_Label8, "YYYY");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_editslot);
    lv_obj_set_width(ui_Panel8, 97);
    lv_obj_set_height(ui_Panel8, 28);
    lv_obj_set_x(ui_Panel8, 171);
    lv_obj_set_y(ui_Panel8, 36);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xC3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthLabelEditslot = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_MonthLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonthLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonthLabelEditslot, 214);
    lv_obj_set_y(ui_MonthLabelEditslot, 50);
    lv_label_set_text(ui_MonthLabelEditslot, "01");
    lv_obj_set_style_text_color(ui_MonthLabelEditslot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MonthLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MonthLabelEditslot, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 212);
    lv_obj_set_y(ui_Label10, 38);
    lv_label_set_text(ui_Label10, "MM");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_editslot);
    lv_obj_set_width(ui_Panel9, 97);
    lv_obj_set_height(ui_Panel9, 28);
    lv_obj_set_x(ui_Panel9, 310);
    lv_obj_set_y(ui_Panel9, 36);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xC3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabelEditslot = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_DateLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabelEditslot, 352);
    lv_obj_set_y(ui_DateLabelEditslot, 50);
    lv_label_set_text(ui_DateLabelEditslot, "01");
    lv_obj_set_style_text_color(ui_DateLabelEditslot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabelEditslot, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 351);
    lv_obj_set_y(ui_Label12, 38);
    lv_label_set_text(ui_Label12, "DD");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 194);
    lv_obj_set_y(ui_Label13, 108);
    lv_label_set_text(ui_Label13, "SAVE");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 214);
    lv_obj_set_y(ui_Label14, 71);
    lv_label_set_text(ui_Label14, ":");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinLabelEditslot = lv_label_create(ui_editslot);
    lv_obj_set_width(ui_MinLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinLabelEditslot, 227);
    lv_obj_set_y(ui_MinLabelEditslot, 71);
    lv_label_set_text(ui_MinLabelEditslot, "00");
    lv_obj_set_style_text_color(ui_MinLabelEditslot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinLabelEditslot, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_editslot_screen_destroy(void)
{
    if(ui_editslot) lv_obj_del(ui_editslot);

    // NULL screen variables
    ui_editslot = NULL;
    ui_Panel6 = NULL;
    ui_editSlotPanel = NULL;
    ui_iconImage3 = NULL;
    ui_okLabel3 = NULL;
    ui_boxImage3 = NULL;
    ui_backLabel3 = NULL;
    ui_btnSaveEditslot = NULL;
    ui_HourLabelEditslot = NULL;
    ui_Label5 = NULL;
    ui_Panel7 = NULL;
    ui_YearLabelEditslot = NULL;
    ui_Label8 = NULL;
    ui_Panel8 = NULL;
    ui_MonthLabelEditslot = NULL;
    ui_Label10 = NULL;
    ui_Panel9 = NULL;
    ui_DateLabelEditslot = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_MinLabelEditslot = NULL;

}
