// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_EDITSLOT1_H
#define UI_EDITSLOT1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_editslot1
extern void ui_editslot1_screen_init(void);
extern void ui_editslot1_screen_destroy(void);
extern lv_obj_t * ui_editslot1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_editSlotPanel1;
extern lv_obj_t * ui_iconImage3;
extern lv_obj_t * ui_okLabel3;
extern lv_obj_t * ui_boxImage3;
extern lv_obj_t * ui_backLabel3;
extern lv_obj_t * ui_btnSaveEditslot1;
extern lv_obj_t * ui_HourLabelEditslot1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_amtLabelEditslot1;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_DateLabelEditslot1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_MinLabelEditslot1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_actLabelEditslot1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

