// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_EDITSLOT_H
#define UI_EDITSLOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_editslot
extern void ui_editslot_screen_init(void);
extern void ui_editslot_screen_destroy(void);
extern lv_obj_t * ui_editslot;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_editSlotPanel;
extern lv_obj_t * ui_iconImage5;
extern lv_obj_t * ui_okLabel5;
extern lv_obj_t * ui_boxImage5;
extern lv_obj_t * ui_backLabel5;
extern lv_obj_t * ui_btnSaveEditslot;
extern lv_obj_t * ui_HourLabelEditslot;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_YearLabelEditslot;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_MonthLabelEditslot;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_DateLabelEditslot;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_MinLabelEditslot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

