// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_EDITSLOT_H
#define UI_EDITSLOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_editslot
extern void ui_editslot_screen_init(void);
extern void ui_editslot_screen_destroy(void);
extern lv_obj_t * ui_editslot;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_editSlotPanel;
extern lv_obj_t * ui_iconImage3;
extern lv_obj_t * ui_okLabel3;
extern lv_obj_t * ui_boxImage3;
extern lv_obj_t * ui_backLabel3;
extern lv_obj_t * ui_btnSaveEditslot;
extern lv_obj_t * ui_HourLabelEditslot;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_YearLabelEditslot;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_MonthLabelEditslot;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_DateLabelEditslot;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_MinLabelEditslot;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

