// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_editslot1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_editSlotPanel1 = NULL;
lv_obj_t * ui_iconImage3 = NULL;
lv_obj_t * ui_okLabel3 = NULL;
lv_obj_t * ui_boxImage3 = NULL;
lv_obj_t * ui_backLabel3 = NULL;
lv_obj_t * ui_btnSaveEditslot1 = NULL;
lv_obj_t * ui_HourLabelEditslot1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_MonthLabelEditslot1 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_DateLabelEditslot1 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_MinLabelEditslot1 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_actLabelEditslot = NULL;
// event funtions

// build funtions

void ui_editslot1_screen_init(void)
{
    ui_editslot1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_editslot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_editslot1);
    lv_obj_set_width(ui_Panel6, 428);
    lv_obj_set_height(ui_Panel6, 30);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_editSlotPanel1 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_editSlotPanel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_editSlotPanel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_editSlotPanel1, 166);
    lv_obj_set_y(ui_editSlotPanel1, 7);
    lv_label_set_text(ui_editSlotPanel1, "EDIT SLOT 4");
    lv_obj_set_style_text_color(ui_editSlotPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_editSlotPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_editSlotPanel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconImage3 = lv_image_create(ui_editslot1);
    lv_image_set_src(ui_iconImage3, &ui_img_1388130735);
    lv_obj_set_width(ui_iconImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconImage3, 9);
    lv_obj_set_y(ui_iconImage3, 6);
    lv_obj_add_flag(ui_iconImage3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLabel3 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_okLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okLabel3, 30);
    lv_obj_set_y(ui_okLabel3, 7);
    lv_label_set_text(ui_okLabel3, "OK (SETUP)");
    lv_obj_set_style_text_color(ui_okLabel3, lv_color_hex(0x41C173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_okLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_okLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boxImage3 = lv_image_create(ui_editslot1);
    lv_image_set_src(ui_boxImage3, &ui_img_1649062918);
    lv_obj_set_width(ui_boxImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boxImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boxImage3, 397);
    lv_obj_set_y(ui_boxImage3, 6);
    lv_obj_add_flag(ui_boxImage3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_boxImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backLabel3 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_backLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabel3, 311);
    lv_obj_set_y(ui_backLabel3, 8);
    lv_label_set_text(ui_backLabel3, "BACK (OPEN)");
    lv_obj_set_style_text_color(ui_backLabel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveEditslot1 = lv_button_create(ui_editslot1);
    lv_obj_set_width(ui_btnSaveEditslot1, 428);
    lv_obj_set_height(ui_btnSaveEditslot1, 25);
    lv_obj_set_x(ui_btnSaveEditslot1, 0);
    lv_obj_set_y(ui_btnSaveEditslot1, 117);
    lv_obj_add_flag(ui_btnSaveEditslot1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSaveEditslot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSaveEditslot1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSaveEditslot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSaveEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSaveEditslot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSaveEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSaveEditslot1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnSaveEditslot1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourLabelEditslot1 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_HourLabelEditslot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabelEditslot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabelEditslot1, 24);
    lv_obj_set_y(ui_HourLabelEditslot1, 51);
    lv_label_set_text(ui_HourLabelEditslot1, "22");
    lv_obj_set_style_text_color(ui_HourLabelEditslot1, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourLabelEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourLabelEditslot1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_editslot1);
    lv_obj_set_width(ui_Panel8, 232);
    lv_obj_set_height(ui_Panel8, 28);
    lv_obj_set_x(ui_Panel8, 183);
    lv_obj_set_y(ui_Panel8, 40);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xC3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthLabelEditslot1 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_MonthLabelEditslot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonthLabelEditslot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonthLabelEditslot1, 360);
    lv_obj_set_y(ui_MonthLabelEditslot1, 45);
    lv_label_set_text(ui_MonthLabelEditslot1, "01");
    lv_obj_set_style_text_color(ui_MonthLabelEditslot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MonthLabelEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MonthLabelEditslot1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_editslot1);
    lv_obj_set_width(ui_Panel9, 232);
    lv_obj_set_height(ui_Panel9, 28);
    lv_obj_set_x(ui_Panel9, 183);
    lv_obj_set_y(ui_Panel9, 77);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xC3CDE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabelEditslot1 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_DateLabelEditslot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabelEditslot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabelEditslot1, 202);
    lv_obj_set_y(ui_DateLabelEditslot1, 83);
    lv_label_set_text(ui_DateLabelEditslot1, "ACT");
    lv_obj_set_style_text_color(ui_DateLabelEditslot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabelEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabelEditslot1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 192);
    lv_obj_set_y(ui_Label13, 121);
    lv_label_set_text(ui_Label13, "SAVE");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 72);
    lv_obj_set_y(ui_Label14, 49);
    lv_label_set_text(ui_Label14, ":");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinLabelEditslot1 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_MinLabelEditslot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinLabelEditslot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinLabelEditslot1, 89);
    lv_obj_set_y(ui_MinLabelEditslot1, 51);
    lv_label_set_text(ui_MinLabelEditslot1, "00");
    lv_obj_set_style_text_color(ui_MinLabelEditslot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinLabelEditslot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinLabelEditslot1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_editslot1);
    lv_obj_set_width(ui_Panel7, 1);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, 158);
    lv_obj_set_y(ui_Panel7, 45);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 202);
    lv_obj_set_y(ui_Label10, 45);
    lv_label_set_text(ui_Label10, "AMT");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actLabelEditslot = lv_label_create(ui_editslot1);
    lv_obj_set_width(ui_actLabelEditslot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_actLabelEditslot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_actLabelEditslot, 357);
    lv_obj_set_y(ui_actLabelEditslot, 82);
    lv_label_set_text(ui_actLabelEditslot, "OFF");
    lv_obj_set_style_text_color(ui_actLabelEditslot, lv_color_hex(0xFC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actLabelEditslot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actLabelEditslot, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_editslot1_screen_destroy(void)
{
    if(ui_editslot1) lv_obj_del(ui_editslot1);

    // NULL screen variables
    ui_editslot1 = NULL;
    ui_Panel6 = NULL;
    ui_editSlotPanel1 = NULL;
    ui_iconImage3 = NULL;
    ui_okLabel3 = NULL;
    ui_boxImage3 = NULL;
    ui_backLabel3 = NULL;
    ui_btnSaveEditslot1 = NULL;
    ui_HourLabelEditslot1 = NULL;
    ui_Panel8 = NULL;
    ui_MonthLabelEditslot1 = NULL;
    ui_Panel9 = NULL;
    ui_DateLabelEditslot1 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_MinLabelEditslot1 = NULL;
    ui_Panel7 = NULL;
    ui_Label10 = NULL;
    ui_actLabelEditslot = NULL;

}
