// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HOME_SCREEN_H
#define UI_HOME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home_screen
extern void ui_home_screen_screen_init(void);
extern void ui_home_screen_screen_destroy(void);
extern lv_obj_t * ui_home_screen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_cur_time;
extern lv_obj_t * ui_cur_date;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_next_meal_time;
extern lv_obj_t * ui_volume;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_home_screen;
extern lv_obj_t * uic_cur_time;
extern lv_obj_t * uic_cur_date;
extern lv_obj_t * uic_next_meal_time;
extern lv_obj_t * uic_volume;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

