// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_info = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_settingLabel3 = NULL;
lv_obj_t * ui_iconImage4 = NULL;
lv_obj_t * ui_okLabel4 = NULL;
lv_obj_t * ui_boxImage4 = NULL;
lv_obj_t * ui_backLabel4 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_nameLabelInfo = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_fwLabelInfo = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_modelLabelInfo = NULL;
lv_obj_t * ui_serialLabelInfo = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions

// build funtions

void ui_info_screen_init(void)
{
    ui_info = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel10, 428);
    lv_obj_set_height(ui_Panel10, 30);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingLabel3 = lv_label_create(ui_info);
    lv_obj_set_width(ui_settingLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingLabel3, 193);
    lv_obj_set_y(ui_settingLabel3, 8);
    lv_label_set_text(ui_settingLabel3, "INFO");
    lv_obj_set_style_text_color(ui_settingLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconImage4 = lv_image_create(ui_info);
    lv_image_set_src(ui_iconImage4, &ui_img_1388130735);
    lv_obj_set_width(ui_iconImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconImage4, 9);
    lv_obj_set_y(ui_iconImage4, 6);
    lv_obj_add_flag(ui_iconImage4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLabel4 = lv_label_create(ui_info);
    lv_obj_set_width(ui_okLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okLabel4, 30);
    lv_obj_set_y(ui_okLabel4, 7);
    lv_label_set_text(ui_okLabel4, "OK (SETUP)");
    lv_obj_set_style_text_color(ui_okLabel4, lv_color_hex(0x41C173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_okLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_okLabel4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boxImage4 = lv_image_create(ui_info);
    lv_image_set_src(ui_boxImage4, &ui_img_1649062918);
    lv_obj_set_width(ui_boxImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boxImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boxImage4, 397);
    lv_obj_set_y(ui_boxImage4, 6);
    lv_obj_add_flag(ui_boxImage4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_boxImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backLabel4 = lv_label_create(ui_info);
    lv_obj_set_width(ui_backLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabel4, 311);
    lv_obj_set_y(ui_backLabel4, 7);
    lv_label_set_text(ui_backLabel4, "BACK (OPEN)");
    lv_obj_set_style_text_color(ui_backLabel4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backLabel4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel11, 159);
    lv_obj_set_height(ui_Panel11, 40);
    lv_obj_set_x(ui_Panel11, 38);
    lv_obj_set_y(ui_Panel11, 36);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0xA4BFF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel11, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nameLabelInfo = lv_label_create(ui_info);
    lv_obj_set_width(ui_nameLabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameLabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameLabelInfo, 95);
    lv_obj_set_y(ui_nameLabelInfo, 56);
    lv_label_set_text(ui_nameLabelInfo, "FEEDER");
    lv_obj_set_style_text_color(ui_nameLabelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nameLabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nameLabelInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 105);
    lv_obj_set_y(ui_Label7, 40);
    lv_label_set_text(ui_Label7, "NAME");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel12, 159);
    lv_obj_set_height(ui_Panel12, 40);
    lv_obj_set_x(ui_Panel12, 38);
    lv_obj_set_y(ui_Panel12, 82);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0xA4BFF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel12, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwLabelInfo = lv_label_create(ui_info);
    lv_obj_set_width(ui_fwLabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwLabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fwLabelInfo, 100);
    lv_obj_set_y(ui_fwLabelInfo, 102);
    lv_label_set_text(ui_fwLabelInfo, "v1.2.0");
    lv_obj_set_style_text_color(ui_fwLabelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fwLabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fwLabelInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 92);
    lv_obj_set_y(ui_Label4, 86);
    lv_label_set_text(ui_Label4, "FW VERSION");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel13, 159);
    lv_obj_set_height(ui_Panel13, 40);
    lv_obj_set_x(ui_Panel13, 230);
    lv_obj_set_y(ui_Panel13, 36);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0xA4BFF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel13, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 297);
    lv_obj_set_y(ui_Label9, 40);
    lv_label_set_text(ui_Label9, "MODEL");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_info);
    lv_obj_set_width(ui_Panel14, 159);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, 230);
    lv_obj_set_y(ui_Panel14, 82);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0xA4BFF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel14, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modelLabelInfo = lv_label_create(ui_info);
    lv_obj_set_width(ui_modelLabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_modelLabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_modelLabelInfo, 287);
    lv_obj_set_y(ui_modelLabelInfo, 56);
    lv_label_set_text(ui_modelLabelInfo, "SF-2025");
    lv_obj_set_style_text_color(ui_modelLabelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_modelLabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_modelLabelInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_serialLabelInfo = lv_label_create(ui_info);
    lv_obj_set_width(ui_serialLabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_serialLabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_serialLabelInfo, 281);
    lv_obj_set_y(ui_serialLabelInfo, 102);
    lv_label_set_text(ui_serialLabelInfo, "X9998877");
    lv_obj_set_style_text_color(ui_serialLabelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_serialLabelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_serialLabelInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_info);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 297);
    lv_obj_set_y(ui_Label11, 86);
    lv_label_set_text(ui_Label11, "SERIAL");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xA5B2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_info_screen_destroy(void)
{
    if(ui_info) lv_obj_del(ui_info);

    // NULL screen variables
    ui_info = NULL;
    ui_Panel10 = NULL;
    ui_settingLabel3 = NULL;
    ui_iconImage4 = NULL;
    ui_okLabel4 = NULL;
    ui_boxImage4 = NULL;
    ui_backLabel4 = NULL;
    ui_Panel11 = NULL;
    ui_nameLabelInfo = NULL;
    ui_Label7 = NULL;
    ui_Panel12 = NULL;
    ui_fwLabelInfo = NULL;
    ui_Label4 = NULL;
    ui_Panel13 = NULL;
    ui_Label9 = NULL;
    ui_Panel14 = NULL;
    ui_modelLabelInfo = NULL;
    ui_serialLabelInfo = NULL;
    ui_Label11 = NULL;

}
