// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LEARNING_H
#define UI_LEARNING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Learning
extern void ui_Learning_screen_init(void);
extern void ui_Learning_screen_destroy(void);
extern lv_obj_t * ui_Learning;
extern lv_obj_t * ui_learningAddcard;
extern lv_obj_t * ui_Learning_container;
extern lv_obj_t * ui_Scanning;
extern lv_obj_t * ui_iconcard;
extern lv_obj_t * ui_press_to_lean;
extern lv_obj_t * ui_detected_cat;
extern lv_obj_t * ui_new_cat;
extern lv_obj_t * ui_cat_ID;
extern lv_obj_t * ui_press_to_save;
extern lv_obj_t * ui_canninglable;
extern lv_obj_t * ui_saved_image;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Learning;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

