// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Learning;
lv_obj_t * ui_Learning = NULL;
lv_obj_t * ui_learningAddcard = NULL;
lv_obj_t * ui_Learning_container = NULL;
lv_obj_t * ui_Scanning = NULL;
lv_obj_t * ui_iconcard = NULL;
lv_obj_t * ui_press_to_lean = NULL;
lv_obj_t * ui_detected_cat = NULL;
lv_obj_t * ui_new_cat = NULL;
lv_obj_t * ui_cat_ID = NULL;
lv_obj_t * ui_press_to_save = NULL;
lv_obj_t * ui_canninglable = NULL;
lv_obj_t * ui_saved_image = NULL;
// event funtions

// build funtions

void ui_Learning_screen_init(void)
{
    ui_Learning = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Learning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_learningAddcard = lv_image_create(ui_Learning);
    lv_image_set_src(ui_learningAddcard, &ui_img_learning_png);
    lv_obj_set_width(ui_learningAddcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_learningAddcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_learningAddcard, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_learningAddcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Learning_container = lv_obj_create(ui_Learning);
    lv_obj_remove_style_all(ui_Learning_container);
    lv_obj_set_width(ui_Learning_container, 114);
    lv_obj_set_height(ui_Learning_container, 97);
    lv_obj_set_x(ui_Learning_container, -6);
    lv_obj_set_y(ui_Learning_container, 15);
    lv_obj_set_align(ui_Learning_container, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Learning_container, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Learning_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scanning = lv_label_create(ui_Learning_container);
    lv_obj_set_width(ui_Scanning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scanning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scanning, -1);
    lv_obj_set_y(ui_Scanning, 17);
    lv_obj_set_align(ui_Scanning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scanning, "ADD CAT");
    lv_obj_set_style_text_font(ui_Scanning, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconcard = lv_image_create(ui_Learning_container);
    lv_image_set_src(ui_iconcard, &ui_img_iconcard_png);
    lv_obj_set_width(ui_iconcard, LV_SIZE_CONTENT);   /// 71
    lv_obj_set_height(ui_iconcard, LV_SIZE_CONTENT);    /// 58
    lv_obj_set_x(ui_iconcard, -2);
    lv_obj_set_y(ui_iconcard, -22);
    lv_obj_set_align(ui_iconcard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconcard, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_press_to_lean = lv_label_create(ui_Learning_container);
    lv_obj_set_width(ui_press_to_lean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_press_to_lean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_press_to_lean, 1);
    lv_obj_set_y(ui_press_to_lean, 38);
    lv_obj_set_align(ui_press_to_lean, LV_ALIGN_CENTER);
    lv_label_set_text(ui_press_to_lean, "press to learn");
    lv_obj_set_style_text_font(ui_press_to_lean, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detected_cat = lv_obj_create(ui_Learning);
    lv_obj_remove_style_all(ui_detected_cat);
    lv_obj_set_width(ui_detected_cat, 236);
    lv_obj_set_height(ui_detected_cat, 97);
    lv_obj_set_x(ui_detected_cat, -5);
    lv_obj_set_y(ui_detected_cat, 15);
    lv_obj_set_align(ui_detected_cat, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_detected_cat, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_new_cat = lv_label_create(ui_detected_cat);
    lv_obj_set_width(ui_new_cat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_new_cat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_new_cat, 6);
    lv_obj_set_y(ui_new_cat, 7);
    lv_obj_set_align(ui_new_cat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_new_cat, "NEW-CAT");
    lv_obj_set_style_text_font(ui_new_cat, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cat_ID = lv_label_create(ui_detected_cat);
    lv_obj_set_width(ui_cat_ID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cat_ID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cat_ID, 2);
    lv_obj_set_y(ui_cat_ID, -26);
    lv_obj_set_align(ui_cat_ID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cat_ID, "1111111111111111111");
    lv_obj_set_style_text_font(ui_cat_ID, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_press_to_save = lv_label_create(ui_detected_cat);
    lv_obj_set_width(ui_press_to_save, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_press_to_save, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_press_to_save, 10);
    lv_obj_set_y(ui_press_to_save, 33);
    lv_obj_set_align(ui_press_to_save, LV_ALIGN_CENTER);
    lv_label_set_text(ui_press_to_save, "PRESS LEAN TO SAVE");
    lv_obj_set_style_text_font(ui_press_to_save, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_canninglable = lv_label_create(ui_Learning);
    lv_obj_set_width(ui_canninglable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_canninglable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_canninglable, 3);
    lv_obj_set_y(ui_canninglable, 10);
    lv_obj_set_align(ui_canninglable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_canninglable, "SCANNING...");
    lv_obj_add_flag(ui_canninglable, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_canninglable, lv_color_hex(0x1A33B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_canninglable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_canninglable, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saved_image = lv_image_create(ui_Learning);
    lv_image_set_src(ui_saved_image, &ui_img_saved_image_png);
    lv_obj_set_width(ui_saved_image, LV_SIZE_CONTENT);   /// 133
    lv_obj_set_height(ui_saved_image, LV_SIZE_CONTENT);    /// 87
    lv_obj_set_x(ui_saved_image, -4);
    lv_obj_set_y(ui_saved_image, 16);
    lv_obj_set_align(ui_saved_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saved_image, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_saved_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Learning = ui_Learning;

}

void ui_Learning_screen_destroy(void)
{
    if(ui_Learning) lv_obj_del(ui_Learning);

    // NULL screen variables
    uic_Learning = NULL;
    ui_Learning = NULL;
    ui_learningAddcard = NULL;
    ui_Learning_container = NULL;
    ui_Scanning = NULL;
    ui_iconcard = NULL;
    ui_press_to_lean = NULL;
    ui_detected_cat = NULL;
    ui_new_cat = NULL;
    ui_cat_ID = NULL;
    ui_press_to_save = NULL;
    ui_canninglable = NULL;
    ui_saved_image = NULL;

}
