// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PLAYBACKIMAGE_H
#define UI_PLAYBACKIMAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_playbackImage
extern void ui_playbackImage_screen_init(void);
extern void ui_playbackImage_screen_destroy(void);
extern lv_obj_t * ui_playbackImage;
extern lv_obj_t * ui_playingImage;
extern lv_obj_t * ui_recordImage;
extern lv_obj_t * ui_pausedImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

