// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PLAYBACK_H
#define UI_PLAYBACK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_playback
extern void ui_playback_screen_init(void);
extern void ui_playback_screen_destroy(void);
extern lv_obj_t * ui_playback;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_settingLabel2;
extern lv_obj_t * ui_iconImage2;
extern lv_obj_t * ui_okLabel2;
extern lv_obj_t * ui_boxImage2;
extern lv_obj_t * ui_backLabel2;
extern lv_obj_t * ui_btnYesPlayback;
extern lv_obj_t * ui_yesLabelPlayback;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_btnNoPlayback;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

