// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_recordingImage = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions

// build funtions

void ui_recordingImage_screen_init(void)
{
    ui_recordingImage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_recordingImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_recordingImage);
    lv_image_set_src(ui_Image4, &ui_img_recording_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_recordingImage_screen_destroy(void)
{
    if(ui_recordingImage) lv_obj_del(ui_recordingImage);

    // NULL screen variables
    ui_recordingImage = NULL;
    ui_Image4 = NULL;

}
