// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_ImageInfo;
lv_obj_t * uic_LabelInfo;
lv_obj_t * uic_btnInfo;
lv_obj_t * uic_LabelTime;
lv_obj_t * uic_ImageTime;
lv_obj_t * uic_btnTime;
lv_obj_t * uic_ImageAudio;
lv_obj_t * uic_audioLabel;
lv_obj_t * uic_btnAudio;
lv_obj_t * uic_ImageSchedule;
lv_obj_t * uic_scheduleLabel;
lv_obj_t * uic_btnSchedule;
lv_obj_t * uic_backLabel;
lv_obj_t * uic_boxImage;
lv_obj_t * uic_okLabel;
lv_obj_t * uic_iconImage;
lv_obj_t * uic_settingLabel;
lv_obj_t * ui_SETTINGS = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_settingLabel = NULL;
lv_obj_t * ui_iconImage = NULL;
lv_obj_t * ui_okLabel = NULL;
lv_obj_t * ui_boxImage = NULL;
lv_obj_t * ui_backLabel = NULL;
lv_obj_t * ui_btnSchedule = NULL;
lv_obj_t * ui_scheduleLabel = NULL;
lv_obj_t * ui_ImageSchedule = NULL;
lv_obj_t * ui_btnAudio = NULL;
lv_obj_t * ui_audioLabel = NULL;
lv_obj_t * ui_ImageAudio = NULL;
lv_obj_t * ui_btnTime = NULL;
lv_obj_t * ui_ImageTime = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_btnInfo = NULL;
lv_obj_t * ui_LabelInfo = NULL;
lv_obj_t * ui_ImageInfo = NULL;
// event funtions

// build funtions

void ui_SETTINGS_screen_init(void)
{
    ui_SETTINGS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SETTINGS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_SETTINGS);
    lv_obj_set_width(ui_Panel3, 428);
    lv_obj_set_height(ui_Panel3, 28);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingLabel = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_settingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingLabel, 188);
    lv_obj_set_y(ui_settingLabel, 8);
    lv_label_set_text(ui_settingLabel, "SETTINGS");
    lv_obj_set_style_text_color(ui_settingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconImage = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_iconImage, &ui_img_1388130735);
    lv_obj_set_width(ui_iconImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconImage, 9);
    lv_obj_set_y(ui_iconImage, 5);
    lv_obj_add_flag(ui_iconImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLabel = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_okLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okLabel, 32);
    lv_obj_set_y(ui_okLabel, 10);
    lv_label_set_text(ui_okLabel, "OK (SETUP)");
    lv_obj_set_style_text_color(ui_okLabel, lv_color_hex(0x41C173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_okLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_okLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boxImage = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_boxImage, &ui_img_1649062918);
    lv_obj_set_width(ui_boxImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boxImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boxImage, 397);
    lv_obj_set_y(ui_boxImage, 6);
    lv_obj_add_flag(ui_boxImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_boxImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backLabel = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_backLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabel, 339);
    lv_obj_set_y(ui_backLabel, 10);
    lv_label_set_text(ui_backLabel, "BACK (OPEN)");
    lv_obj_set_style_text_color(ui_backLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSchedule = lv_button_create(ui_SETTINGS);
    lv_obj_set_width(ui_btnSchedule, 214);
    lv_obj_set_height(ui_btnSchedule, 50);
    lv_obj_set_x(ui_btnSchedule, 0);
    lv_obj_set_y(ui_btnSchedule, 28);
    lv_obj_add_flag(ui_btnSchedule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSchedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSchedule, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSchedule, lv_color_hex(0xEFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSchedule, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSchedule, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnSchedule, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scheduleLabel = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_scheduleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scheduleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scheduleLabel, 72);
    lv_obj_set_y(ui_scheduleLabel, 58);
    lv_label_set_text(ui_scheduleLabel, "SCHEDULE");
    lv_obj_set_style_text_font(ui_scheduleLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSchedule = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_ImageSchedule, &ui_img_419196496);
    lv_obj_set_width(ui_ImageSchedule, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSchedule, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSchedule, 88);
    lv_obj_set_y(ui_ImageSchedule, 34);
    lv_obj_add_flag(ui_ImageSchedule, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSchedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnAudio = lv_button_create(ui_SETTINGS);
    lv_obj_set_width(ui_btnAudio, 214);
    lv_obj_set_height(ui_btnAudio, 50);
    lv_obj_set_x(ui_btnAudio, 0);
    lv_obj_set_y(ui_btnAudio, 78);
    lv_obj_add_flag(ui_btnAudio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnAudio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnAudio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnAudio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnAudio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnAudio, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnAudio, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audioLabel = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_audioLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audioLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audioLabel, 83);
    lv_obj_set_y(ui_audioLabel, 109);
    lv_label_set_text(ui_audioLabel, "AUDIO");
    lv_obj_set_style_text_font(ui_audioLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageAudio = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_ImageAudio, &ui_img_336627466);
    lv_obj_set_width(ui_ImageAudio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAudio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAudio, 88);
    lv_obj_set_y(ui_ImageAudio, 85);
    lv_obj_add_flag(ui_ImageAudio, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageAudio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnTime = lv_button_create(ui_SETTINGS);
    lv_obj_set_width(ui_btnTime, 214);
    lv_obj_set_height(ui_btnTime, 50);
    lv_obj_set_x(ui_btnTime, 214);
    lv_obj_set_y(ui_btnTime, 28);
    lv_obj_add_flag(ui_btnTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnTime, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTime = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_ImageTime, &ui_img_1236581539);
    lv_obj_set_width(ui_ImageTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTime, 311);
    lv_obj_set_y(ui_ImageTime, 35);
    lv_obj_add_flag(ui_ImageTime, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 310);
    lv_obj_set_y(ui_LabelTime, 59);
    lv_label_set_text(ui_LabelTime, "TIME");
    lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnInfo = lv_button_create(ui_SETTINGS);
    lv_obj_set_width(ui_btnInfo, 214);
    lv_obj_set_height(ui_btnInfo, 50);
    lv_obj_set_x(ui_btnInfo, 214);
    lv_obj_set_y(ui_btnInfo, 78);
    lv_obj_add_flag(ui_btnInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnInfo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInfo = lv_label_create(ui_SETTINGS);
    lv_obj_set_width(ui_LabelInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInfo, 311);
    lv_obj_set_y(ui_LabelInfo, 111);
    lv_label_set_text(ui_LabelInfo, "INFO");
    lv_obj_set_style_text_font(ui_LabelInfo, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageInfo = lv_image_create(ui_SETTINGS);
    lv_image_set_src(ui_ImageInfo, &ui_img_1476654543);
    lv_obj_set_width(ui_ImageInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageInfo, 311);
    lv_obj_set_y(ui_ImageInfo, 85);
    lv_obj_add_flag(ui_ImageInfo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_settingLabel = ui_settingLabel;
    uic_iconImage = ui_iconImage;
    uic_okLabel = ui_okLabel;
    uic_boxImage = ui_boxImage;
    uic_backLabel = ui_backLabel;
    uic_btnSchedule = ui_btnSchedule;
    uic_scheduleLabel = ui_scheduleLabel;
    uic_ImageSchedule = ui_ImageSchedule;
    uic_btnAudio = ui_btnAudio;
    uic_audioLabel = ui_audioLabel;
    uic_ImageAudio = ui_ImageAudio;
    uic_btnTime = ui_btnTime;
    uic_ImageTime = ui_ImageTime;
    uic_LabelTime = ui_LabelTime;
    uic_btnInfo = ui_btnInfo;
    uic_LabelInfo = ui_LabelInfo;
    uic_ImageInfo = ui_ImageInfo;

}

void ui_SETTINGS_screen_destroy(void)
{
    if(ui_SETTINGS) lv_obj_del(ui_SETTINGS);

    // NULL screen variables
    ui_SETTINGS = NULL;
    ui_Panel3 = NULL;
    uic_settingLabel = NULL;
    ui_settingLabel = NULL;
    uic_iconImage = NULL;
    ui_iconImage = NULL;
    uic_okLabel = NULL;
    ui_okLabel = NULL;
    uic_boxImage = NULL;
    ui_boxImage = NULL;
    uic_backLabel = NULL;
    ui_backLabel = NULL;
    uic_btnSchedule = NULL;
    ui_btnSchedule = NULL;
    uic_scheduleLabel = NULL;
    ui_scheduleLabel = NULL;
    uic_ImageSchedule = NULL;
    ui_ImageSchedule = NULL;
    uic_btnAudio = NULL;
    ui_btnAudio = NULL;
    uic_audioLabel = NULL;
    ui_audioLabel = NULL;
    uic_ImageAudio = NULL;
    ui_ImageAudio = NULL;
    uic_btnTime = NULL;
    ui_btnTime = NULL;
    uic_ImageTime = NULL;
    ui_ImageTime = NULL;
    uic_LabelTime = NULL;
    ui_LabelTime = NULL;
    uic_btnInfo = NULL;
    ui_btnInfo = NULL;
    uic_LabelInfo = NULL;
    ui_LabelInfo = NULL;
    uic_ImageInfo = NULL;
    ui_ImageInfo = NULL;

}
