// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_settingLabel;
extern lv_obj_t * ui_iconImage;
extern lv_obj_t * ui_okLabel;
extern lv_obj_t * ui_boxImage;
extern lv_obj_t * ui_backLabel;
extern lv_obj_t * ui_btnSchedule;
extern lv_obj_t * ui_scheduleLabel;
extern lv_obj_t * ui_ImageSchedule;
extern lv_obj_t * ui_btnAudio;
extern lv_obj_t * ui_audioLabel;
extern lv_obj_t * ui_ImageAudio;
extern lv_obj_t * ui_btnTime;
extern lv_obj_t * ui_ImageTime;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_btnInfo;
extern lv_obj_t * ui_LabelInfo;
extern lv_obj_t * ui_ImageInfo;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settingLabel;
extern lv_obj_t * uic_iconImage;
extern lv_obj_t * uic_okLabel;
extern lv_obj_t * uic_boxImage;
extern lv_obj_t * uic_backLabel;
extern lv_obj_t * uic_btnSchedule;
extern lv_obj_t * uic_scheduleLabel;
extern lv_obj_t * uic_ImageSchedule;
extern lv_obj_t * uic_btnAudio;
extern lv_obj_t * uic_audioLabel;
extern lv_obj_t * uic_ImageAudio;
extern lv_obj_t * uic_btnTime;
extern lv_obj_t * uic_ImageTime;
extern lv_obj_t * uic_LabelTime;
extern lv_obj_t * uic_btnInfo;
extern lv_obj_t * uic_LabelInfo;
extern lv_obj_t * uic_ImageInfo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

