// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCHEDULE_H
#define UI_SCHEDULE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_schedule
extern void ui_schedule_screen_init(void);
extern void ui_schedule_screen_destroy(void);
extern lv_obj_t * ui_schedule;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_editSlotPanel2;
extern lv_obj_t * ui_iconImage6;
extern lv_obj_t * ui_okLabel6;
extern lv_obj_t * ui_boxImage6;
extern lv_obj_t * ui_backLabel6;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_buttonPanelSchedule;
extern lv_obj_t * ui_btnoption1Schedule;
extern lv_obj_t * ui_labeltime1Schedule;
extern lv_obj_t * ui_labelamt1Schedule;
extern lv_obj_t * ui_imageon1Schedule;
extern lv_obj_t * ui_btnoption2Schedule;
extern lv_obj_t * ui_imageon2Schedule;
extern lv_obj_t * ui_labelamt2Schedule;
extern lv_obj_t * ui_labeltime2Schedule;
extern lv_obj_t * ui_btnoption3Schedule;
extern lv_obj_t * ui_imageon3Schedule;
extern lv_obj_t * ui_labeltime3Schedule;
extern lv_obj_t * ui_labelamt3Schedule;
extern lv_obj_t * ui_btnoption4Schedule;
extern lv_obj_t * ui_imageon4Schedule;
extern lv_obj_t * ui_labeltime4Schedule;
extern lv_obj_t * ui_labelamt4Schedule;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

