// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCHEDULE_H
#define UI_SCHEDULE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_schedule
extern void ui_schedule_screen_init(void);
extern void ui_schedule_screen_destroy(void);
extern lv_obj_t * ui_schedule;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_editSlotPanel2;
extern lv_obj_t * ui_iconImage6;
extern lv_obj_t * ui_okLabel6;
extern lv_obj_t * ui_boxImage6;
extern lv_obj_t * ui_backLabel6;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_buttonPanelSchedule;
extern lv_obj_t * ui_btnSaveEditslot2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_btnSaveEditslot3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_btnSaveEditslot4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

