// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_schedule = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_settingLabel2 = NULL;
lv_obj_t * ui_iconImage2 = NULL;
lv_obj_t * ui_okLabel2 = NULL;
lv_obj_t * ui_boxImage2 = NULL;
lv_obj_t * ui_backLabel2 = NULL;
lv_obj_t * ui_btnYesSchedule = NULL;
lv_obj_t * ui_yesLabelSchedule = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_btnYesSchedule1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_schedule_screen_init(void)
{
    ui_schedule = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_schedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_schedule);
    lv_obj_set_width(ui_Panel5, 428);
    lv_obj_set_height(ui_Panel5, 28);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingLabel2 = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_settingLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingLabel2, 188);
    lv_obj_set_y(ui_settingLabel2, 8);
    lv_label_set_text(ui_settingLabel2, "SCHEDULE");
    lv_obj_set_style_text_color(ui_settingLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingLabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconImage2 = lv_image_create(ui_schedule);
    lv_image_set_src(ui_iconImage2, &ui_img_1388130735);
    lv_obj_set_width(ui_iconImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconImage2, 9);
    lv_obj_set_y(ui_iconImage2, 5);
    lv_obj_add_flag(ui_iconImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_iconImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okLabel2 = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_okLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_okLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_okLabel2, 32);
    lv_obj_set_y(ui_okLabel2, 10);
    lv_label_set_text(ui_okLabel2, "OK (SETUP)");
    lv_obj_set_style_text_color(ui_okLabel2, lv_color_hex(0x41C173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_okLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_okLabel2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boxImage2 = lv_image_create(ui_schedule);
    lv_image_set_src(ui_boxImage2, &ui_img_1649062918);
    lv_obj_set_width(ui_boxImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boxImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boxImage2, 397);
    lv_obj_set_y(ui_boxImage2, 6);
    lv_obj_add_flag(ui_boxImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_boxImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backLabel2 = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_backLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backLabel2, 339);
    lv_obj_set_y(ui_backLabel2, 10);
    lv_label_set_text(ui_backLabel2, "BACK (OPEN)");
    lv_obj_set_style_text_color(ui_backLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backLabel2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnYesSchedule = lv_button_create(ui_schedule);
    lv_obj_set_width(ui_btnYesSchedule, 100);
    lv_obj_set_height(ui_btnYesSchedule, 25);
    lv_obj_set_x(ui_btnYesSchedule, 102);
    lv_obj_set_y(ui_btnYesSchedule, 80);
    lv_obj_add_flag(ui_btnYesSchedule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnYesSchedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnYesSchedule, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnYesSchedule, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnYesSchedule, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnYesSchedule, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yesLabelSchedule = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_yesLabelSchedule, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yesLabelSchedule, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yesLabelSchedule, 123);
    lv_obj_set_y(ui_yesLabelSchedule, 84);
    lv_label_set_text(ui_yesLabelSchedule, "YES");
    lv_obj_set_style_text_color(ui_yesLabelSchedule, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yesLabelSchedule, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yesLabelSchedule, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_schedule);
    lv_image_set_src(ui_Image1, &ui_img_yes20x20_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 159);
    lv_obj_set_y(ui_Image1, 82);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnYesSchedule1 = lv_button_create(ui_schedule);
    lv_obj_set_width(ui_btnYesSchedule1, 100);
    lv_obj_set_height(ui_btnYesSchedule1, 25);
    lv_obj_set_x(ui_btnYesSchedule1, 222);
    lv_obj_set_y(ui_btnYesSchedule1, 80);
    lv_obj_add_flag(ui_btnYesSchedule1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnYesSchedule1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnYesSchedule1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnYesSchedule1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnYesSchedule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnYesSchedule1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnYesSchedule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnYesSchedule1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnYesSchedule1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 243);
    lv_obj_set_y(ui_Label1, 84);
    lv_label_set_text(ui_Label1, "NO");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_schedule);
    lv_image_set_src(ui_Image2, &ui_img_no20x20_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 279);
    lv_obj_set_y(ui_Image2, 83);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_schedule);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 160);
    lv_obj_set_y(ui_Label2, 47);
    lv_label_set_text(ui_Label2, "SAVE RECORD?	");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_schedule_screen_destroy(void)
{
    if(ui_schedule) lv_obj_del(ui_schedule);

    // NULL screen variables
    ui_schedule = NULL;
    ui_Panel5 = NULL;
    ui_settingLabel2 = NULL;
    ui_iconImage2 = NULL;
    ui_okLabel2 = NULL;
    ui_boxImage2 = NULL;
    ui_backLabel2 = NULL;
    ui_btnYesSchedule = NULL;
    ui_yesLabelSchedule = NULL;
    ui_Image1 = NULL;
    ui_btnYesSchedule1 = NULL;
    ui_Label1 = NULL;
    ui_Image2 = NULL;
    ui_Label2 = NULL;

}
